### PR TITLE
Add Fixed Lower  to Version Triage Plane (with some refactors)

### LINKED ISSUE #131: Add Fixed Low Version item to Version Triage Plane
- 希望在Version Triage 页面添加已修复的低版本号信息
- 这个信息会作为QA进行Triage操作的判断依据: 低版本已修复的问题在当前版本必须approved

### PR DESCRIPTION
**Pull request by MimeLyc**
Issue Number: close #131 
- Review by commits is recommened
- Refactor is done mainly toward method FindIssueRelationInfo
- Tested by UI because there is few additional logic change.

### CODE REVIEW

File: internal/entity/version_triage.go [hunk 1]
```diff
@@ -18,6 +18,9 @@ type VersionTriage struct {
 	DueTime             *time.Time                `json:"due_time,omitempty"`
 	Comment             string                    `json:"comment,omitempty"`
 	ChangedItem         VersionTriageChangedItem  `json:"changed_item,omitempty"`
+
+	// TODO: temporaly maintain the merge status in the DO until there is isolated model in the service layer and the controller layer
+	MergeStatus VersionTriageMergeStatus `gorm:"-" json:"merge_status,omitempty"`
```
Comment (VelocityLight) [inline internal/entity/version_triage.go:23]: 1.MergeStatus is declared but not used？
2.Is database table updated ?

**Review by VelocityLight — APPROVED** [review]

File: internal/entity/version_triage.go (hunk 1 above)
Comment (VelocityLight) [inline internal/entity/version_triage.go:23]: 1. MergeStatus is declared but not used？
2. Is database table updated ？

Comment (MimeLyc) [reply internal/entity/version_triage.go:23]: 1. MergeStatus is only presented in front-end and will not persistent in db.
2. The status is maintained here because the VersionTriage model is used from front-end to db entity, it'll be removed to VO after refactor.
