### PR TITLE
Fix Issue: Released triages have wrong value.

### LINKED ISSUE #117: Version triages have wrong value if the version is released.
image

### PR DESCRIPTION
**Pull request by MimeLyc**
Issue Number: close #117 
The reason is that there is none related logic to deal with released status of version triage.

### CODE REVIEW

File: website/src/components/issues/renderer/mapper.js [hunk 1]
```diff
@@ -15,7 +15,8 @@ export function mapPickStatusToFrontend(pick) {
         unknown: "unknown",
         later: "later",
         "won't fix": "won't fix",
-        "accept(frozen)": "approved(frozen)"
+        "accept(frozen)": "approved(frozen)",
+        "released": "released"
```
Comment (VelocityLight) [inline website/src/components/issues/renderer/mapper.js:19]: actually it shows "released in x.y.z" in UI, is changeable in another javascript function

File: internal/service/version_triage_info.go [hunk 2]
```diff
@@ -119,7 +119,7 @@ func SelectVersionTriageInfo(query *dto.VersionTriageInfoQuery) (*dto.VersionTri
 
 	// compose
 	var versionTriages []entity.VersionTriage
-	if releaseVersion.Status == entity.ReleaseVersionStatusUpcoming {
+	if releaseVersion.Status == entity.ReleaseVersionStatusUpcoming || releaseVersion.Status == entity.ReleaseVersionStatusFrozen {
```
Comment (VelocityLight) [inline internal/service/version_triage_info.go:122]: if version frozen,  we still need to show all issues ?

**Review by VelocityLight — APPROVED** [review]

File: internal/service/version_triage_info.go (hunk 2 above)
Comment (MimeLyc) [reply internal/service/version_triage_info.go:122]: Yep, by 尹苏
